version: '3.7'

x-custom:
  rails: &rails
    build: ./api
    depends_on:
      - db
    environment:
      DEVELOPMENT_DB_HOST: db
      DEVELOPMENT_DB_PASSWORD: password
      DEVELOPMENT_SMTP_ADDRESS: mailhog
      DEVELOPMENT_SMTP_PORT: 1025
      SITE_HOST: localhost
      SPRING_TMP_PATH: /api/tmp/spring
      TEST_DB_HOST: db
      TEST_DB_PASSWORD: password
    stdin_open: true
    tty: true
    volumes:
      - ./api:/api
      - bundle:/usr/local/bundle

services:
  api:
    <<: *rails
    command: ["bin/rails", "s", "puma"]
    container_name: docker-sample_api
    ports:
      - '3000:3000'
  spring:
    <<: *rails
    container_name: docker-sample_spring
    command: bin/spring server
  db:
    command: ["--sql_mode=NO_ENGINE_SUBSTITUTION"]
    container_name: docker-sample_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
  mailhog:
    build: ./mailhog
    container_name: docker-sample_mailhog
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp/mailhog
      MH_OUTGOING_SMTP: /home/mailhog/outgoing_smtp.json
    volumes:
      - maildir:/tmp/mailhog
      - ./mailhog:/home/mailhog
    ports:
      - '8025:8025'

volumes:
  bundle:
    name: docker-sample_api_bundle
  mysql:
    name: docker-sample_db_mysql
  maildir:
    name: docker-sample_mailhog_maildir
