version: '3.7'

x-custom:
  rails: &rails
    build: ./api
    depends_on:
      - db
    environment:
      DEVELOPMENT_DB_HOST: db
      DEVELOPMENT_DB_PASSWORD: password
      SPRING_TMP_PATH: /api/tmp/spring
      TEST_DB_HOST: db
      TEST_DB_PASSWORD: password
    stdin_open: true
    tty: true
    volumes:
      - ./api:/api
      - bundle:/usr/local/bundle

services:
  api:
    <<: *rails
    command: bin/rails s puma
    container_name: docker-sample_api
    ports:
      - '3000:3000'
  spring:
    <<: *rails
    container_name: docker-sample_spring
    command: bin/spring server
  db:
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    container_name: docker-sample_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql

volumes:
  bundle:
    name: docker-sample_api_bundle
  mysql:
    name: docker-sample_db_mysql
